# Generated by Django 5.0.7 on 2024-08-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0003_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("athlete_id", models.IntegerField(db_index=True)),
                ("refresh_token_code", models.CharField(db_index=True, max_length=255)),
                ("scope", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ShortLivedAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("athlete_id", models.IntegerField(db_index=True)),
                ("scope", models.BooleanField()),
                ("access_token_code", models.CharField(db_index=True, max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
