# Generated by Django 5.0.7 on 2024-08-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titles", "0004_refreshtoken_shortlivedaccesstoken_delete_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="token",
            name="token_type",
        ),
        migrations.RemoveField(
            model_name="token",
            name="user",
        ),
        migrations.AddField(
            model_name="token",
            name="athlete_id",
            field=models.IntegerField(db_index=True, default=23193264),
            preserve_default=False,
        ),
    ]
