# Generated by Django 5.0.7 on 2024-08-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("titles", "0005_remove_token_scope_remove_token_token_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RefreshToken",
        ),
        migrations.DeleteModel(
            name="ShortLivedAccessToken",
        ),
        migrations.AddField(
            model_name="title",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
