# Generated by Django 5.0.8 on 2024-09-05 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("titles", "0006_delete_refreshtoken_delete_shortlivedaccesstoken_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question",
        ),
    ]
